## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

- name: "baremetal-deploy : BEGIN"
  delegate_to: localhost
  block:

      ##
      ##    NOTE: All tasks here are blocked and delegated to execute
      ##          on the deployhost/localhost 
      ##

      ##
      ##    Log in to the IPMI service to determine state if power is off
      ## 
      ##    NOTE: username and password should be in
      ##          the encrypted credentials.yml file
      ##



      - set_fact:
          deploy_node: false

      - name: "baremetal-deploy : ipmi verify machine power is off"
        shell:
          cmd: |
            ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ xtoph_deploy.hardware_profile.ipmi.get_power }} | grep -q 'off'
        vars:
          t_uid: "{{ ipmi_credentials[ipmi_fqdn]['username'] | default(ipmi_credentials['default']['username']) }}"
          t_pw:  "{{ ipmi_credentials[ipmi_fqdn]['password'] | default(ipmi_credentials['default']['password']) }}"
        register: vminfo_result
        ignore_errors: true
        when: 
          - xtoph_deploy.kickstart_profile is defined and
            xtoph_deploy.kickstart_profile.method == "pxe" and
            ipmi_fqdn is defined

      - set_fact:
          deploy_node: true
        when:
          - xtoph_deploy.kickstart_profile is defined and
            xtoph_deploy.kickstart_profile.method == "pxe" and
            ipmi_fqdn is defined and
            vminfo_result.rc == 0


    
- delegate_to: localhost
  block:



      ##
      ##    All tasks here are blocked and 
      ##    delegated to execute on the deployhost
      ##
      ##
      ##    WHEN:
      ##      always
      ##
      ##
      ##    NOTE:
      ##
      ##      this section is blocked primarily to follow the 
      ##      flow of other platforms, although here we do
      ##      NOT test for 'node_deploy'.  Some baremetal
      ##      deployuments are manual and we cannot always test
      ##      the machine status with ipmi.
      ##
      ##      so we always prepare media, kickstart configs, etc...
      ##      based on the template parameters ... but relay on
      ##      the user to manually engage pxe (when ipmi is not
      ##      available)
      ##
      ##



      - block:

    
    
          ##
          ##    Create the custom ISO for the OS installation
          ##
          ##    * NOTE * to avoid concurrency problems with
          ##             disk space and i/o bandwidth, we
          ##             use serial at the import_task level
          ##             DO NOT use "throttle" here as a stop gap
          ##
    
    
    
          - name: "baremetal-deploy : test iso availability"
            stat:
              path: "{{ xtoph_deploy.deployhost.iso.dir }}/{{ xtoph_deploy.kickstart_profile.boot_iso }}"
            register: iso_result
    
          - fail:
              msg: "Specified ISO does not exist: {{ xtoph_deploy.deployhost.iso.dir }}/{{ xtoph_deploy.kickstart_profile.boot_iso }}"
            when: not iso_result.stat.exists
     
          - name: "baremetal-deploy : clone ISO source to temp workspace"
            vars:
              t_isofile: "{{ xtoph_deploy.deployhost.iso.dir }}/{{ xtoph_deploy.kickstart_profile.boot_iso }}"
              t_destdir: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso"
            shell:
              cmd: |
                xorriso -osirrox on -indev "{{ t_isofile }}" -extract / "{{ t_destdir }}"
      
          - name: "baremetal-deploy : preserve the ISO volume id"
            vars:
              t_isofile: "{{ xtoph_deploy.deployhost.iso.dir }}/{{ xtoph_deploy.kickstart_profile.boot_iso }}"
            shell:
              cmd: |
                isoinfo -d -i {{ t_isofile }} | grep 'Volume id:' | sed -e 's/Volume id: //g'
            register: isoinfo_volume_id
    
    
    
          ##
          ##    Create the kickstart config for the ISO
          ##
    
    
    
          - name: "baremetal-deploy : create kickstart http dir '{{ xtoph_deploy.deployhost.kickstart.dir }}'"
            file: path="{{ xtoph_deploy.deployhost.kickstart.dir }}" mode="0755" state=directory
          
              
          - name: "baremetal-deploy : deploy kickstart config iso temp workspace"
            vars:
              p_ssh_key:    "{{ lookup('file','/root/.ssh/id_rsa.pub') }}"
              p_diskDevice: "{{ xtoph_deploy.hardware_profile.disk.dev }}"
            template:
              src:   "{{ xtoph_deploy.kickstart_profile.template }}"
              dest:  "{{ item }}"
              owner: root
              group: root
              mode: 0444
            loop:
              - "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/ks.cfg"
    
    
        
          ##
          ##    Adjust the isolinux.cfg (BIOS)
          ##
      
      
      
          - name: "baremetal-deploy : isolinux.cfg: change default timeout to 3 seconds"
            replace:
              path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg"
              regexp: '^timeout(\s+.*)?$'
              replace: 'timeout 30'
          
          - name: "baremetal-deploy : remove default menu option from isolinux.cfg"
            lineinfile:
              dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg"
              regexp: "^.*menu default.*$"
              state:  absent
          
          - name: "baremetal-deploy : set new default menu option in isolinux.cfg"
            lineinfile:
              dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg"
              insertafter: "^.*label linux.*$"
              line: "  menu default"
              state: present
    
    
    
          ##
          ##    Adjust the grub.cfg (UEFI)
          ##
        
        
    
          - name: "baremetal-deploy : grub.cfg : change default timeout to 3 seconds"
            replace:
              path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/EFI/BOOT/grub.cfg"
              regexp: '^set timeout=.*$'
              replace: 'set timeout=30'
        
          - name: "baremetal-deploy : grub.cfg : change default menu option"
            replace:
              path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/EFI/BOOT/grub.cfg"
              regexp: '^set default=.*$'
              replace: 'set default="0"'
     
    
    
          ##
          ##    NOTE:
          ##
          ##      Reference: 'man -7 dracut.cmdline', format for static ip= is as follows:
          ##
          ##        ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<dns1>][:<dns2>]]
          ##
          ##      Reference: http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames
          ##
          ##        interface names 'enoX = onboard', 'ensX = pci-express', 'enp2s0 = physical location', 'enxYYYYYYYYYYYY = macaddress'
          ##
          ##      More discussions:
          ##
          ##        https://fedoraproject.org/wiki/Dracut/Options#Network
          ##        https://bugzilla.redhat.com/show_bug.cgi?id=836039
          ##



          - block:
   
              ##
              ##    All tasks in this block are related to
              ##    kernel parameter adjustments for 
              ##    the installation media
              ##
              ##    * NOTE * vars are defined once for the 
              ##             for the whole block at the end
              ##             of the block
              ##
      
              - name: "baremetal-deploy : isolinux.cfg : kernel args for BIOS iso (cdrom install)"
                replace:
                  path:   "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg"
                  regexp: '(\s+)append(\s+.*)?$'
                  replace: >
                      \1append\2
                      inst.text
                      inst.ks={{ t_ks_hd }}
                      ksdevice={{ t_net_dev }} 
                      ip={{ t_net_ip }}::{{ t_net_gw }}:{{ t_net_nm }}::{{ t_net_dev }}:none
                      nameserver={{ t_net_dns }}
                when: xtoph_deploy.kickstart_profile.method == "cdrom"
     
              - name: "baremetal-deploy : grub.cfg : kernel args for UEFI iso (cdrom install)"
                replace:
                  path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/EFI/BOOT/grub.cfg"
                  regexp: '(\s+)linuxefi(\s+.*)?$'
                  replace: >
                      \1linuxefi\2 
                      inst.text
                      inst.ks={{ t_ks_hd }}
                      ksdevice={{ t_net_dev }} 
                      ip={{ t_net_ip }}::{{ t_net_gw }}:{{ t_net_nm }}::{{ t_net_dev }}:none
                      nameserver={{ t_net_dns }} 
                when: xtoph_deploy.kickstart_profile.method == "cdrom"
    
              - name: "baremetal-deploy : isolinux.cfg : kernel args for BIOS boot-iso (network install)"
                replace:
                  path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg"
                  regexp: '(\s+)append(\s+.*)?$'
                  replace: >
                      \1append\2
                      inst.text
                      inst.ks={{ t_ks_url }}
                      inst.repo={{ t_ks_repo }}
                      ksdevice={{ t_net_dev }} 
                      ip={{ t_net_ip }}::{{ t_net_gw }}:{{ t_net_nm }}::{{ t_net_dev }}:none
                      nameserver={{ t_net_dns }}
                when: xtoph_deploy.kickstart_profile.method == "network"
    
              - name: "baremetal-deploy : grub.cfg : kernel args for UEFI boot-iso (network install)"
                replace:
                  path: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/EFI/BOOT/grub.cfg"
                  regexp: '(\s+)linuxefi(\s+.*)?$'
                  replace: >
                      \1linuxefi\2 
                      inst.text
                      inst.ks={{ t_ks_url }}
                      inst.repo={{ t_ks_repo }}
                      ksdevice={{ t_net_dev }} 
                      ip={{ t_net_ip }}::{{ t_net_gw }}:{{ t_net_nm }}::{{ t_net_dev }}:none
                      nameserver={{ t_net_dns }} 
                when: xtoph_deploy.kickstart_profile.method == "network"
    
        
        
            vars:
              t_net_dev:  "{{ xtoph_deploy.hardware_profile.network.dev   }}"
              t_net_ip:   "{{ xtoph_deploy.network.default.ip      }}"
              t_net_nm:   "{{ xtoph_deploy.network.default.netmask }}"
              t_net_gw:   "{{ xtoph_deploy.network.default.gateway }}"
              t_net_dns:  "{{ xtoph_deploy.deployhost.ip if xtoph_deploy.deployhost.dnsmasq_asprimary == true else xtoph_deploy.network.default.nameserver }}"
              t_ks_repo:  "{{ xtoph_deploy.deployhost.repos.url }}/{{ xtoph_deploy.kickstart_profile.mnt }}"
              t_ks_hd:    "hd:LABEL={{ isoinfo_volume_id.stdout | replace(' ','\\x20') }}"
              t_ks_url:   "{{ xtoph_deploy.deployhost.kickstart.url }}/{{ g_clusterName }}-{{ inventory_hostname }}.cfg"
      
            ## End-Of-Block
      
      
      
          ##
          ##    Preserve some files in the temp workspace
          ##    artifacts directory for easy debugging
          ##
    
    
        
          - name: "baremetal-deploy : copy files to temp workspace artifacts directory for preservation"
            copy:
              dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts"
              src:  "{{ item }}"
            loop:
              - "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/isolinux/isolinux.cfg" 
              - "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/ks.cfg" 
              - "{{ xtoph_deploy.deployhost.tmp_dir }}/iso/EFI/BOOT/grub.cfg"
               
  
      
          ##
          ##    Generate the custom ISO image
          ##
    
    
    
          - name: "baremetal-deploy : create script to generate iso"
            vars:
              t_iso_label:  "{{ isoinfo_volume_id.stdout }}"
              t_iso_source: "{{ xtoph_deploy.deployhost.tmp_dir }}/iso"
              t_iso_output: "{{ xtoph_deploy.deployhost.tmp_dir }}/{{ xtoph_deploy.baremetal.vm.name }}.iso"
            template:
              src: "mkiso.j2"
              dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/mkiso.sh"
              owner: root
              group: root
              mode: 0755
         
          - name: "baremetal-deploy : execute mkiso.sh script"
            shell:
              cmd: |
                {{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/mkiso.sh
        
    
    
          ##
          ##    Transfer the ISO image to baremetal storage location
          ##
          ##    NOTE: to avoid concurrency problems with
          ##          disk space and i/o bandwidth, we
          ##          set 'throttle: 1'
          ##
    
       
     
          - name: "baremetal-deploy : upload iso image"
            throttle: 1
            copy:
              src: "{{ xtoph_deploy.deployhost.tmp_dir }}/{{ xtoph_deploy.baremetal.vm.name }}.iso"
              dest: "{{ xtoph_deploy.deployhost.iso.dir }}"
    
          - name: "baremetal-deploy : clean-up temporary work-space"
            shell:
              cmd: |
                if [[ -d "{{ xtoph_deploy.deployhost.tmp_dir }}/iso" ]] ; then
                  rm -rf "{{ xtoph_deploy.deployhost.tmp_dir }}/iso"
                fi
    
                if [[ -e "{{ xtoph_deploy.deployhost.tmp_dir }}/{{ xtoph_deploy.baremetal.vm.name }}.iso" ]] ; then
                  rm -f "{{ xtoph_deploy.deployhost.tmp_dir }}/{{ xtoph_deploy.baremetal.vm.name }}.iso"
                fi
            when: xtoph_deploy.cleanup == true

        when: xtoph_deploy.kickstart_profile is defined and
              xtoph_deploy.kickstart_profile.method != "pxe"



      ##
      ##    Create the kickstart config for PXE/NETWORK supported installs
      ##



      - block:

          - name: "baremetal-deploy : create kickstart http dir '{{ xtoph_deploy.deployhost.kickstart.dir }}'"
            file: path="{{ xtoph_deploy.deployhost.kickstart.dir }}" mode="0755" state=directory


          - name: "baremetal-deploy : deploy kickstart config iso to http dir"
            vars:
              p_ssh_key:    "{{ lookup('file','/root/.ssh/id_rsa.pub') }}"
              p_diskDevice: "{{ xtoph_deploy.hardware_profile.disk.dev }}"
            template:
              src:   "{{ xtoph_deploy.kickstart_profile.template }}"
              dest:  "{{ item }}"
              owner: root
              group: root
              mode: 0444
            loop:
              - "{{ xtoph_deploy.deployhost.kickstart.dir }}/{{ g_clusterName }}-{{ inventory_hostname }}.cfg"

        when: xtoph_deploy.kickstart_profile is defined and
              xtoph_deploy.kickstart_profile.template is defined and
              xtoph_deploy.kickstart_profile.method == "pxe" 



      ##
      ##    Execute baremetal ipmi calls to automate installation
      ##



      - block:

          - name: "baremetal-deploy : ipmi config steps"
            shell:
              cmd: |
                ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ item }}
            loop:
              "{{ xtoph_deploy.hardware_profile.ipmi.config_steps }}"
    
          - name: "baremetal-deploy : ipmi set power on"
            shell:
              cmd: |
                ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ xtoph_deploy.hardware_profile.ipmi.power_on }}

        vars:
          t_uid: "{{ ipmi_credentials[ipmi_fqdn]['username'] | default(ipmi_credentials['default']['username']) }}"
          t_pw:  "{{ ipmi_credentials[ipmi_fqdn]['password'] | default(ipmi_credentials['default']['password']) }}"
        when: 
          - xtoph_deploy.hardware_profile.ipmi is defined and
            deploy_node == true



  ##
  ## End-Of-Block
  ##

