##   Christoph Doerbeck
##
## Summary:
##

- name: "baremetal-undeploy : BEGIN"
  delegate_to: localhost
  block:



      ##
      ##    NOTE: All tasks here are delegated to execute
      ##          on the deployhost/localhost
      ##



      ##
      ##    Execute baremetal ipmi calls to power off system
      ##
  
      - block:
  
          - name: "baremetal-undeploy : (ipmi) set power off"
            shell:
              cmd: |
                ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ xtoph_deploy.machine_profile.ipmi.power_off }}
            ignore_errors: yes
  
        vars:
          t_uid: "{{ ipmi_credentials[ipmi_fqdn]['username'] | default(ipmi_credentials['default']['username']) }}"
          t_pw:  "{{ ipmi_credentials[ipmi_fqdn]['password'] | default(ipmi_credentials['default']['password']) }}"
        when:
          - xtoph_deploy.machine_profile.ipmi.fqdn is defined
          - xtoph_deploy.machine_profile.ipmi.fqdn|length > 0
          - xtoph_deploy.kickstart_profile.method == "pxe"



      ##
      ##    Execute baremetal BMC calls to power off system 
      ##    and eject virtual media
      ##
  
      - block:

            - name: "baremetal-undeploy : (BMC) debug"
              debug:
                 msg:
                   - "BMC Address         : {{ t_bmc }}"
                   - "BMC Login Status    : {{ xtoph_deploy.machine_profile.bmc.login_status }}"
                   - "BMC Power Status    : {{ xtoph_deploy.machine_profile.bmc.power_status }}"
                   - "BMC Power On        : {{ xtoph_deploy.machine_profile.bmc.power_on }}"
                   - "BMC Power Off       : {{ xtoph_deploy.machine_profile.bmc.power_off }}"
                   - "BMC VMedia Status   : {{ xtoph_deploy.machine_profile.bmc.media_status }}"
                   - "BMC VMedia Eject    : {{ xtoph_deploy.machine_profile.bmc.media_eject }}"
              when:
                - xtoph_deploy.debug == true

            - name: "baremetal-undeploy : (BMC) login-status"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.login_status }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
                  --chomp

            - name: "baremetal-undeploy : (BMC) power-status"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.power_status }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
                  --chomp
              register: bmc_result

            - name: "baremetal-undeploy : (BMC) power-off"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.power_off }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
              when: bmc_result.stdout == "on" 

            - name: "baremetal-undeploy : (BMC) wait for power-status = off"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.power_status }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
                  --chomp
              register: local_result
              until: local_result.stdout == "off"
              retries: 600
              delay: 5
              when:
                - bmc_result.stdout == "on" 

            - name: "baremetal-undeploy : (BMC) media-status"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.media_status }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
                  --chomp
              register: bmc_result
              when:
                - xtoph_deploy.kickstart_profile.method != "pxe"
      
            - name: "baremetal-undeploy : (BMC) media-eject"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.media_eject }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
              when:
                - xtoph_deploy.kickstart_profile.method != "pxe"
                - bmc_result.stdout == "inserted"

            - name: "baremetal-undeploy : (BMC) wait for media-status = ejected"
              script: >
                  {{ xtoph_deploy.machine_profile.bmc.media_status }}
                  -u {{ t_user }}
                  -p {{ t_pass }}
                  -i {{ t_bmc }}
                  --chomp
              register: local_result
              until: local_result.stdout == "ejected"
              retries: 600
              delay: 5
              when:
                - xtoph_deploy.kickstart_profile.method != "pxe"
                - bmc_result.stdout == "inserted"

  
        vars:
          t_bmc:    "{{ xtoph_deploy.machine_profile.bmc.fqdn }}"
          t_user:   "{{ bmc_credentials[bmc_fqdn]['username'] | default(bmc_credentials['default']['username']) }}"
          t_pass:   "{{ bmc_credentials[bmc_fqdn]['password'] | default(bmc_credentials['default']['password']) }}"
        when:
          - xtoph_deploy.machine_profile.bmc.fqdn is defined
          - xtoph_deploy.machine_profile.bmc.fqdn|length > 0

