##   Christoph Doerbeck
##
## Summary:
##

- name: "baremetal-undeploy : BEGIN"
  delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the deployhost/localhost
    ##



    ##
    ##    Execute baremetal ipmi calls to power off system
    ##

    - block:

        - name: "baremetal-undeploy : ipmi set power off"
          throttle: 1
          shell:
            cmd: |
              ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ xtoph_deploy.machine_profile.ipmi.power_off }}
          ignore_errors: yes

      vars:
        t_uid: "{{ ipmi_credentials[ipmi_fqdn]['username'] | default(ipmi_credentials['default']['username']) }}"
        t_pw:  "{{ ipmi_credentials[ipmi_fqdn]['password'] | default(ipmi_credentials['default']['password']) }}"
      when:
        - xtoph_deploy.kickstart_profile is defined and
          xtoph_deploy.kickstart_profile.method == "pxe" and
          ipmi_fqdn is defined

