##   Christoph Doerbeck
##
## Summary:
##

- name: "baremetal-undeploy : BEGIN"
  delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the deployhost/localhost
    ##



    ##
    ##    Execute baremetal ipmi calls to power off system
    ##

    - block:

        - name: "baremetal-undeploy : (ipmi) set power off"
          throttle: 1
          shell:
            cmd: |
              ipmitool -U {{ t_uid }} -P {{ t_pw }} -H {{ ipmi_fqdn }} {{ xtoph_deploy.machine_profile.ipmi.power_off }}
          ignore_errors: yes

      vars:
        t_uid: "{{ ipmi_credentials[ipmi_fqdn]['username'] | default(ipmi_credentials['default']['username']) }}"
        t_pw:  "{{ ipmi_credentials[ipmi_fqdn]['password'] | default(ipmi_credentials['default']['password']) }}"
      when:
        - xtoph_deploy.kickstart_profile is defined and
          xtoph_deploy.kickstart_profile.method == "pxe" and
          ipmi_fqdn is defined



    ##
    ##    Execute baremetal redfish calls to power off system 
    ##    and eject virtual media
    ##



    - block:

        - name: "baremetal-undeploy : (redfish) set machine power off"
          script: redfish-setpower-off.sh {{ redfish_fqdn }} {{ t_uid }} {{ t_pw }}
          ignore_errors: true

        - name: "baremetal-deploy : (redfish) virtual media eject"
          script:  redfish-virtualmedia-eject.sh {{ redfish_fqdn }} {{ t_uid }} {{ t_pw }}
          ignore_errors: true

      vars:
        t_uid: "{{ redfish_credentials[redfish_fqdn]['username'] | default(redfish_credentials['default']['username']) }}"
        t_pw:  "{{ redfish_credentials[redfish_fqdn]['password'] | default(redfish_credentials['default']['password']) }}"

      when:
        - xtoph_deploy.kickstart_profile is defined and
          xtoph_deploy.kickstart_profile.method != "pxe" and
          redfish_fqdn is defined


