## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##

##
##    Install additional packages
##



- name: "baremetal-setup : install baremetal supporting packages"
  yum: name=ipmitool state=installed



