## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##

##
##    Install additional packages
##


## TO BE DEPRECATED: 20220301
## These steps were incorporated into deployer-setup.yml long ago
##
#- name: "baremetal-setup : install baremetal supporting packages"
#  yum: name=ipmitool,curl state=installed



