
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##




##
##    High level assertions (validation)
##



##
##    All nodes should have xtoph_deploy.deployhost
##    branch of the dictionary defined.  We can assert
##    a few additional sub parameters.
##



- name: "common-assertions : xtoph_deploy.deployhost validation"
  any_errors_fatal: true
  assert:
    that:
      - xtoph_deploy.deployhost is defined
      - xtoph_deploy.deployhost.ip is defined
    success_msg: "Assertion Passed"
    fail_msg: "CONFIG ERROR: assertion listed above means that xtoph_deploy is missing critical data (CHECK YOUR CONFIGS)"



##
##    Nodes that define a platform (which should include
##    every node EXCEPT the deployhost itself) should have
##    a complete xtoph_deploy dictionary.  Validate the major
##    components of the destionary.
##



- name: "common-assertions : xtoph_deploy highlevel validation "
  any_errors_fatal: true
  assert:
    that:
      - xtoph_deploy.platform_profile is defined
      - xtoph_deploy.machine_profile is defined
      - xtoph_deploy.resource_profile is defined
      - xtoph_deploy.kickstart_profile is defined
    fail_msg: "CONFIG ERROR: assertion listed above means that xtoph_deploy is missing critical data (CHECK YOUR CONFIGS)"
    success_msg: "Assertion Passed"
  when:
    - xtoph_deploy.selected_profile.machine != ""


##
##    Nodes that define a machine_profile are only
##    allowed to declare an ipmi OR bmc, not
##    both
##


- name: "common-assertions : assert that machine_profile does NOT enable both 'ipmi' AND 'bmc'"
  any_errors_fatal: true
  assert:
    that:
      - (xtoph_deploy.machine_profile.bmc.fqdn|length == 0 ) or 
        (xtoph_deploy.machine_profile.ipmi.fqdn|length == 0 )
    fail_msg: "CONFIG ERROR: a machine_profile is only allowed bmc OR ipmi, not both (CHECK YOUR CONFIGS)"
    success_msg: "Assertion Passed"
  when:
    - xtoph_deploy.selected_profile.machine != ""
    - xtoph_deploy.machine_profile.platform == "baremetal"


