## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



- delegate_to: localhost
  block:

      ##
      ##    NOTE: All tasks here are blocked and delegated to execute
      ##          on the deployhost/localhost
      ##

      - name: "common-dhcp-postprocess : stop services"
        throttle: 1
        service: name={{ item }} state=stopped enabled=no masked=no
        when: xtoph_deploy.deployhost.dhcp.enable
        with_items:
          - "dhcpd"
          - "tftp"

      - name: "common-dhcp-postprocess : cleanup machine pxe configs for BIOS and EFI"
        vars:
#          t_name: "{{ h_pubMAC | replace(':','-') }}"
          t_name: "{{ xtoph_deploy.machine_profile.network.default.mac | replace(':','-') }}"
        file:
          path:  "{{ item  }}"
          state: absent
        loop:
          - '/var/lib/tftpboot/bios/pxelinux.cfg/01-{{ t_name }}'
          - '/var/lib/tftpboot/efi/grub.cfg-01-{{ t_name }}'
        when: xtoph_deploy.cleanup == true

  when: xtoph_deploy.kickstart_profile.method == "pxe" and
        xtoph_deploy.kickstart_profile.repo_iso is defined and
        xtoph_deploy.kickstart_profile.repo_iso != ""
