## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



##
##    Following block of tasks here are delegated to execute
##    on the deployhost/localhost
##



- delegate_to: localhost
  block:


        - name: "common-finish : common finish tasks"
          debug: msg="No special finish tasks"

