## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the deployhost/localhost
    ##

    ##
    ##    This block groups tasks related
    ##    to finishing a kickstart (ISO) deployment
    ##

    ##
    ##    NOTE: All kickstarts are assumed to shutdown
    ##          at completion.  That's how we know it
    ##          finished.
    ##



    - name: "libvirt-deploy-monitor : wait for shutdown"
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh domstate "{{ xtoph_deploy.platform_profile.vm.name }}" | grep -q "shut off"
      register: result
      until:  result.rc == 0
      retries: 600
      delay: 5
      when: xtoph_deploy.kickstart_profile.wait_for_shutdown == true


    
    - name: "libvirt-deploy-monitor : virtual machine change state to RUNNING (BOOT)"
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh start "{{ xtoph_deploy.platform_profile.vm.name }}"
      when: xtoph_deploy.kickstart_profile.wait_for_shutdown == true



    - name: "libvirt-deploy-monitor : undeploy iso in storage directory"
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      throttle: 1
      file:
        path: "{{ xtoph_deploy.platform_profile.storage.default.qcow_dir }}/{{ xtoph_deploy.platform_profile.vm.name }}.iso"
        state: absent
      when: xtoph_deploy.kickstart_profile.wait_for_shutdown == true



    - name: "libvirt-deploy-monitor : copy async restart monitor to platform host"
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      copy:
        src: libvirt-restart-monitor.sh
        dest: /var/tmp/libvirt-restart-monitor.sh
        mode: 0755
        owner: root
        group: root
      when: xtoph_deploy.kickstart_profile.launch_restart_monitor is defined and
            xtoph_deploy.kickstart_profile.launch_restart_monitor == true



    - name: "libvirt-deploy-monitor : launch async restart monitor"
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      async: 3600
      poll: 0
      shell:
        cmd: >
          /var/tmp/libvirt-restart-monitor.sh
          -d {{ xtoph_deploy.platform_profile.vm.name }}
          -t 3600
          -c 1
          -e "{{ xtoph_deploy.platform_profile.storage.default.qcow_dir }}/{{ xtoph_deploy.platform_profile.vm.name }}.iso"
      when: xtoph_deploy.kickstart_profile.launch_restart_monitor is defined and
            xtoph_deploy.kickstart_profile.launch_restart_monitor == true




  when: deploy_node == true
