##   Christoph Doerbeck
##
## Summary:
##

- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the deployhost/localhost
    ##



    ##
    ##    Stop and Delete Virtual Machine 
    ##



    - name: "libvirt-undeploy : stop virtual machine"
      throttle: 1
      shell:
        cmd: |
          virsh destroy "{{ xtoph_deploy.libvirt.vm.name }}"
      ignore_errors: yes



    - name: "libvirt-undeploy : delete virtual machine"
      throttle: 1
      shell:
        cmd: |
          virsh undefine "{{ xtoph_deploy.libvirt.vm.name }}" --remove-all-storage --nvram
      ignore_errors: yes



    - name: "libvirt-undeploy : undeploy iso in storage directory"
      throttle: 1
      file:
        path: "{{ xtoph_deploy.libvirt.storage.qcow_dir }}/{{ xtoph_deploy.libvirt.vm.name }}.iso"
        state: absent

