##   Christoph Doerbeck
##
## Summary:
##


- name: "libvirt-undeploy : BEGIN"
  delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the localhost (deployhost/controller)
    ##



    ##
    ##    Stop and Delete Virtual Machine 
    ##



    - name: "libvirt-undeploy : stop virtual machine"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh destroy "{{ xtoph_deploy.platform_profile.vm.name }}"
      ignore_errors: yes



    - name: "libvirt-undeploy : delete virtual machine"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh undefine "{{ xtoph_deploy.platform_profile.vm.name }}" --remove-all-storage --nvram
      ignore_errors: yes



    - name: "libvirt-undeploy : undeploy iso in storage directory"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      file:
        path: "{{ xtoph_deploy.platform_profile.storage.default.qcow_dir }}/{{ xtoph_deploy.platform_profile.vm.name }}.iso"
        state: absent



    ##
    ##    Attempt to clean up the libvirt network/interfaces
    ##
    ##    NOTE:  Only macvtap is 1-to-1 with a vm.  Deleting
    ##           a nat or normal bridge network could have
    ##           consequences with other vm, so we don't touch
    ##           those networks.  Maybe in the future, the 
    ##           script can be extended to determine if this
    ##           is the last host, and only then delete it.
    ##



    - name: "libvirt-undeploy : deploy script to cleanup/remove libvirt network"
      template:
        src: "rmnet-libvirt.j2"
        dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/rmnet-libvirt.sh"
        owner: root
        group: root
        mode: 0755
    
    - name: "libvirt-undeploy : execute script to remove libvirt network"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      script:
        cmd: "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/rmnet-libvirt.sh"
      register: rmnet_results
      changed_when: "'CHANGED' in rmnet_results.stdout"
      notify:
        - delegated_restart_dnsmasq
      when: xtoph_deploy.platform_profile.network.default.undeploy | default(false)




