## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



##
##    Following block of tasks here are delegated to execute
##    on the deployhost/localhost
##



- delegate_to: localhost
  block:


        - name: "libvirt-deploy-post : platform post install tasks"
          debug: msg="No special post install tasks for libvirt"

