## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to excute
    ##          on the deployhost/localhost
    ##

    ##
    ##    This block groups tasks related
    ##    to finishing a kickstart (ISO) deployment
    ##

    ##
    ##    NOTE: All kickstarts are assumed to shutdown
    ##          at completion.  That's how we now it
    ##          finished.
    ##



    - name: "libvirt-deploy-monitor : wait for shutdown"
      shell:
        cmd: |
          virsh domstate "{{ xtoph_deploy.libvirt.vm.name }}" | grep -q "shut off"
      register: result
      until:  result.rc == 0
      retries: 600
      delay: 5


    
    - name: "libvirt-deploy-monitor : start node back up"
      shell:
        cmd: |
          virsh start "{{ xtoph_deploy.libvirt.vm.name }}"



  when: deploy_node == true and
        xtoph_deploy.kickstart_profile.wait_for_shutdown == true
