##   Christoph Doerbeck
##
## Summary:
##

- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to excute
    ##          on the deployhost/localhost
    ##



    ##
    ##    Create script to delete the libvirt network
    ##
    ##    NOTE:  at this time, an "undeploy" will NOT
    ##           execute this script and clean up
    ##           libvirt networking.  Currently, it is
    ##           left as a manual step.
    ##
    ##    NOTE:  we don't touch system routes during
    ##           "undeploy".  Again, that's left as 
    ##           manual step.
    ##



    - name: "libvirt-deploy : script to remove libvirt network"
      vars:
      template:
        src: "rmnet-libvirt.j2"
        dest: "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/rmnet-libvirt.sh"
        owner: root
        group: root
        mode: 0755



    #- name: "libvirt-deploy : create libvirt network"
    #  throttle: 1
    #  shell:
    #    cmd: |
    #      bash "{{ xtoph_deploy.deployhost.tmp_dir }}/artifacts/rmnet-libvirt.sh"



    ##
    ##    Stop and Delete Virtual Machine 
    ##



    - name: "libvirt-undeploy : stop virtual machine"
      throttle: 1
      shell:
        cmd: |
          virsh destroy "{{ xtoph_deploy.libvirt.vm.name }}"
      ignore_errors: yes



    - name: "libvirt-undeploy : delete virtual machine"
      throttle: 1
      shell:
        cmd: |
          virsh undefine "{{ xtoph_deploy.libvirt.vm.name }}" --remove-all-storage --nvram
      ignore_errors: yes



    - name: "libvirt-undeploy : undeploy iso in storage directory"
      throttle: 1
      file:
        path: "{{ xtoph_deploy.libvirt.storage.qcow_dir }}/{{ xtoph_deploy.libvirt.vm.name }}.iso"
        state: absent

