##   Christoph Doerbeck
##
## Summary:
##


- name: "libvirt-undeploy : BEGIN"
  delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the localhost (deployhost/controller)
    ##



    ##
    ##    Stop and Delete Virtual Machine 
    ##



    - name: "libvirt-undeploy : stop virtual machine"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh destroy "{{ xtoph_deploy.platform_profile.vm.name }}"
      ignore_errors: yes



    - name: "libvirt-undeploy : delete virtual machine"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      shell:
        cmd: |
          virsh undefine "{{ xtoph_deploy.platform_profile.vm.name }}" --remove-all-storage --nvram
      ignore_errors: yes



    - name: "libvirt-undeploy : undeploy iso in storage directory"
      throttle: 1
      delegate_to: "{{ xtoph_deploy.platform_profile.host_fqdn }}"
      file:
        path: "{{ xtoph_deploy.platform_profile.storage.default.qcow_dir }}/{{ xtoph_deploy.platform_profile.vm.name }}.iso"
        state: absent

