## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to execute
    ##          on the deployhost/localhost
    ##

    ##
    ##    This block groups tasks related
    ##    to finishing a kickstart (ISO) deployment
    ##

    ##
    ##    NOTE: All kickstarts are assumed to shutdown
    ##          at completion.  That's how we know it
    ##          finished.
    ##



    - name: "libvirt-deploy-monitor : wait for shutdown"
      shell:
        cmd: |
          virsh domstate "{{ xtoph_deploy.platform_profile.vm.name }}" | grep -q "shut off"
      register: result
      until:  result.rc == 0
      retries: 600
      delay: 5
      when: xtoph_deploy.kickstart_profile.wait_for_shutdown == true


    
    - name: "libvirt-deploy-monitor : virtual machine change state to RUNNING (BOOT)"
      shell:
        cmd: |
          virsh start "{{ xtoph_deploy.platform_profile.vm.name }}"
      when: xtoph_deploy.kickstart_profile.wait_for_shutdown == true



    - name: "libvirt-deploy-monitor : undeploy iso in storage directory"
      throttle: 1
      file:
        path: "{{ xtoph_deploy.platform_profile.storage.default.qcow_dir }}/{{ xtoph_deploy.platform_profile.vm.name }}.iso"
        state: absent



  when: deploy_node == true
