---



##
##    DEBUG OUTPUT
##



- name: "main.yml : ***** BEGIN XTOPH_DEPLOY ROLE PROCESSING *****"
  debug: msg="inventory_hostname={{ inventory_hostname }} xtoph_deploy_action={{ xtoph_deploy_action }}"



##
##    Load variables
##



- name: "main.yml : loading config variables"
  include_vars:
    file: "../../../config/{{ item }}"
  loop:
    - xtoph-deploy-config.yml
    - credentials.yml

- name: "main.yml : loading xtoph_deploy/vars variables"
  include_vars:
    file: "../vars/{{ item }}"
  loop:
    - defaults.yml
    - resource_profiles.yml
    - hardware_profiles.yml
    - kickstart_profiles.yml



##
##    Combine variables under a single dictionary (xtoph_deploy)
##
##    For the various profiles, we only merge the chunk 
##    relevant to this host (inventory_hostname) which is
##    determined by  xtoph_deploy.selected_profile.XXX variable
## 



- name: "main.yml : merging xtoph_deploy_config into single dictionary called 'xtoph_deploy'"
  set_fact:
    xtoph_deploy: "{{ xtoph_deploy | combine(xtoph_deploy_config, recursive=True) }}"

- name: "main.yml : merge hardware_profile into xtoph_deploy"
  set_fact:
    xtoph_deploy: "{{ xtoph_hardware_profiles[xtoph_deploy.selected_profile.hardware] | combine(xtoph_deploy) }}"
  when: xtoph_deploy.selected_profile.hardware != ''

- name: "main.yml : merge kickstart_profile into xtoph_deploy"
  set_fact:
    xtoph_deploy: "{{ xtoph_kickstart_profiles[xtoph_deploy.selected_profile.kickstart] | combine(xtoph_deploy) }}"
  when: xtoph_deploy.selected_profile.kickstart != ''

- name: "main.yml : merge resource_profile into xtoph_deploy"
  set_fact:
    xtoph_deploy: "{{ xtoph_resource_profiles[xtoph_deploy.selected_profile.resource] | combine(xtoph_deploy) }}"
  when: xtoph_deploy.selected_profile.resource != ''



##
##    If xtoph_deploy.debug is 'true', 
##    dump the current xtoph_deploy dictionary
## 



- debug: var=xtoph_deploy
  when: xtoph_deploy.debug == true



##
##    SETUP
##
##        Run platform setup for each platform defined by 
##        xtoph_deploy.deployhost.platform
##
##        NOTE: xtoph_deploy.deployhost.platform can be a single
##              item or a list.  I use a jinja built-in template
##              filter determine if the key exists is "in" the list
##
##              the platform_item declares the 'platform' and the 
##              'playbook' to include if matched
##



- name: "main.yml : setup common stuff"
  include_tasks: "common-setup.yml"
  when: 
    - xtoph_deploy_action == "setup" 



- name: "main.yml : setup platform specifics"
  include_tasks: "{{ platform_item.tasks }}"
  when: 
    - xtoph_deploy_action == "setup" 
    - platform_item.platform in xtoph_deploy.deployhost.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   tasks: 'libvirt-setup.yml'   } 
    - { platform: 'ovirt',     tasks: 'ovirt-setup.yml'     } 
    - { platform: 'baremetal', tasks: 'baremetal-setup.yml' } 



- name: "main.yml : setup dhcp/pxe"
  include_tasks: "common-dhcp-setup.yml"
  when:
    - xtoph_deploy_action == "setup" 
    - xtoph_deploy.deployhost.dhcp.enable



##
##    UNDEPLOY
##
##        If action == 'undeploy' and the machine's hardware platform 
##        is platform_item.platform, include the platform_item.tasks
##



- name: "main.yml : undeploy machines"
  include_tasks: "{{ platform_item.tasks }}"
  when: 
    - xtoph_deploy_action == "undeploy" 
    - xtoph_deploy.hardware_profile.platform == platform_item.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   tasks: 'libvirt-undeploy.yml'   } 
    - { platform: 'ovirt',     tasks: 'ovirt-undeploy.yml'     } 
    - { platform: 'baremetal', tasks: 'baremetal-undeploy.yml' } 



##
##    PRE-PROCESS
##
##        If action == 'preprocess' and the machine's hardware platform 
##        is platform_item.platform, include the platform_item.tasks
##



- name: "main.yml : platform deploy pre-processing"
  include_tasks: "{{ platform_item.playbook }}"
  when: 
    - xtoph_deploy_action == "preprocess" 
    - xtoph_deploy.hardware_profile.platform == platform_item.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   playbook: 'libvirt-deploy-preprocess.yml'   } 
    - { platform: 'ovirt',     playbook: 'ovirt-deploy-preprocess.yml'     } 
    - { platform: 'baremetal', playbook: 'baremetal-deploy-preprocess.yml' } 



- name: "main.yml : common deploy pre-processing"
  include_tasks: "common-deploy-preprocess.yml"
  when: 
    - xtoph_deploy_action == "preprocess" 



- name: "main.yml : dhcp (pxe) pre-processing"
  include_tasks: "common-dhcp-preprocess.yml"
  when: 
    - xtoph_deploy_action == "preprocess" 
    - xtoph_deploy.deployhost.dhcp.enable
    - xtoph_deploy.kickstart_profile.method   == "pxe"
    - xtoph_deploy.kickstart_profile.repo_iso is defined
    - xtoph_deploy.kickstart_profile.repo_iso != ""



##
##    DEPLOY
##
##        If action == 'deploy' and the machine's hardware platform 
##        is platform_item.platform, include the platform_item.tasks
##



- name: "main.yml : platform deploy machines"
  include_tasks: "{{ platform_item.playbook }}"
  when: 
    - xtoph_deploy_action == "deploy" 
    - xtoph_deploy.hardware_profile.platform == platform_item.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   playbook: 'libvirt-deploy.yml'   } 
    - { platform: 'ovirt',     playbook: 'ovirt-deploy.yml'     } 
    - { platform: 'baremetal', playbook: 'baremetal-deploy.yml' } 



##
##    MONITOR
##
##        If action == 'deploy' and the machine's hardware platform 
##        is platform_item.platform, include the platform_item.tasks
##



- name: "main.yml : platform deployment monitor of machines"
  include_tasks: "{{ platform_item.playbook }}"
  when: 
    - xtoph_deploy_action == "deploy" 
    - xtoph_deploy.hardware_profile.platform == platform_item.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   playbook: 'libvirt-deploy-monitor.yml'   } 
    - { platform: 'ovirt',     playbook: 'ovirt-deploy-monitor.yml'     } 
    - { platform: 'baremetal', playbook: 'baremetal-deploy-monitor.yml' } 



##
##    POST-PROCESS
##
##        If action == 'deploy' and the machine's hardware platform 
##        is platform_item.platform, include the platform_item.tasks
##



- name: "main.yml : platform deployment post-procesing of machines"
  include_tasks: "{{ platform_item.playbook }}"
  when: 
    - xtoph_deploy_action == "deploy" 
    - xtoph_deploy.hardware_profile.platform == platform_item.platform
  loop_control:
    loop_var: platform_item
  with_items:
    - { platform: 'libvirt',   playbook: 'libvirt-deploy-post.yml'   } 
    - { platform: 'ovirt',     playbook: 'ovirt-deploy-post.yml'     } 
    - { platform: 'baremetal', playbook: 'baremetal-deploy-post.yml' } 



- name: "main.yml : common deployment post-processing of machines"
  include_tasks: "common-deploy-post.yml"
  when: 
    - xtoph_deploy_action == "deploy" 



- name: "main.yml : dhcp/pxe post-processing"
  include_tasks: "common-dhcp-post.yml"
  when: 
    - xtoph_deploy_action == "deploy" 
    - xtoph_deploy.deployhost.dhcp.enable
    - xtoph_deploy.kickstart_profile.method   == "pxe"
    - xtoph_deploy.kickstart_profile.repo_iso is defined
    - xtoph_deploy.kickstart_profile.repo_iso != ""



##
##    DEBUG OUTPUT
##



- name: "main.yml : ***** END XTOPH_DEPLOY ROLE PROCESSING *****"
  debug: msg="inventory_hostname={{ inventory_hostname }}  xtoph_deploy_action={{ xtoph_deploy_action }}"

