## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##    These tasks configure the "deployhost" with oVirt support
##    and install software/services to support the deployments
##

##
##    Install the OVIRT SDK 
##



- name: "ovirt-setup : install oVirt sdk/api"
  yum: name=python-ovirt-engine-sdk4 state=installed



##
##    Install additional required packages
##



- name: "ovirt-setup : install supporting packages"
  yum: name=genisoimage,xorriso,git,tree,wget,yum-utils,firewalld,httpd,net-tools,traceroute,nmap state=installed



##
##    Set up ssh keys
##



- name: "ovirt-setup : Create ssh directory"
  file:
    path: /root/.ssh
    mode: "0700"
    state: directory

- name: "ovirt-setup : test deployhost ssh key"
  stat: path="/root/.ssh/id_rsa.pub"
  register: test_ssh_key

- name: "ovirt-setup : create deployhost ssh key"
  command: "ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa"
  when: test_ssh_key.stat.exists == false



##
##   Set up ISO directories 
##



- name: "ovirt-setup : create iso directory"
  file:
    path: "{{ xtoph_deploy.deployhost.iso.dir }}"
    mode: "0755"
    owner: "root"
    group: "root"
    state: directory



##
##   Configure httpd to support kickstarts
##



- name: "ovirt-setup: deploy httpd configuration"
  vars:
    - p_port: "{{ xtoph_deploy.deployhost.http_port }}"
  template:
    src: "deployhost-httpd-conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"
    owner: root
    group: root
    mode: 0644

- name: "ovirt-setup: selinux restorecon on /var/www/html"
  shell: restorecon -R /var/www/html



##
##   Enable system services
##



- name: "ovirt-setup : enable system services"
  service: name="{{ item }}" state=restarted enabled=yes masked=no
  with_items:
    - "NetworkManager"
    - "firewalld"
    - "httpd"



##
##   Enable network services/ports
##



- name: "ovirt-setup : add firewalld services"
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - "http"
    - "https"

- name: "ovirt-setup : add firewalld ports"
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - "{{ xtoph_deploy.deployhost.http_port }}/tcp"



##   
##    NOTE: I should probably just develop a selinux 
##          test to see if port needs to be added  
##   
##    NOTE: If we use a port not natively included 
##          by default selinux profiles, we need to add it
##   
##     - name: "ovirt-ovirt-setup:  add http port to selinux http_port_t"
##     - shell:
##         cmd: |
##           semanage port -a -t http_port_t -p tcp {{ xtoph_deploy.deployhost.http_port }}

