## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



##
##
##



- delegate_to: localhost
  block:

      ##
      ##    NOTE: All tasks here are blocked and delegated to excute
      ##          on the deployhost/localhost when deploy_node = true
      ##


    
      ##
      ##    Update /etc/hosts with hostnames and IPs of new cluster
      ##
      ##    NOTE: to avoid cuncurrency problems editing a single
      ##          file, we set 'throttle = 1'
      ##



      - name: "ovirt-deploy-preprocess : cleanup conflicting IP in /etc/hosts"
        throttle: 1
        lineinfile:
          dest:   "/etc/hosts"
          regexp: "{{ h_pubIP }} .*$"
          state:  absent
      
      - name: "ovirt-deploy-preprocess : cleanup conflicting name in /etc/hosts"
        throttle: 1
        lineinfile:
          dest:   "/etc/hosts"
          regexp: ".*{{ inventory_hostname }}.{{ xtoph_deploy.ovirt.network.net0.fqdn }}.*"
          state:  absent
      
      - name: "ovirt-deploy-preprocess : add entry in /etc/hosts"
        throttle: 1
        lineinfile:
          dest:   "/etc/hosts"
          line:   "{{ h_pubIP }} {{ inventory_hostname }}.{{  xtoph_deploy.ovirt.network.net0.fqdn }}"
          state:  present



      ##
      ##    Create MAC addresses if not already configured
      ##    and store it in the ../config/host_vars directory
      ##
 


      - name: "ovirt-deploy-preprocess : create host_vars dir"
        file: path="{{ lookup('env','PWD') }}/config/host_vars" state=directory
   
      - name: "ovirt-deploy-preprocess : create host_vars file"
        file: path="{{ lookup('env','PWD') }}/config/host_vars/{{ inventory_hostname }}" state=touch
    
      - name: "ovirt-deploy-preprocess : generate random MAC "
        script: macgen.py
        register: macgen_output
        when: h_pubMAC is undefined
    
      - name: "ovirt-deploy-preprocess : store random MAC in host_vars"
        lineinfile:
          dest:   "{{ lookup('env', 'PWD') }}/config/host_vars/{{ inventory_hostname }}"
          line:   "h_pubMAC: '{{ macgen_output.stdout }}'"
          state:  present
        when: h_pubMAC is undefined
        register: makeupmac
    
      - name: "ovirt-deploy-preprocess : set fact to preserve MAC for this run"
        set_fact:
          h_pubMAC: '{{ macgen_output.stdout }}'
        when: makeupmac.changed


