## Authors: 
##   Christoph Doerbeck
##
## Summary:
##



- delegate_to: localhost
  block:



    ##
    ##    NOTE: All tasks here are delegated to excute
    ##          on the deployhost/localhost
    ##

    ##
    ##    Log in to the oVIRT API service
    ##
    ##    * NOTE * username and password should be in
    ##             the encrypted credentials.yml file
    ##



    - name: "ovirt-deploy-monitor : Login to oVirt"
      ovirt_auth:
        hostname: "{{ xtoph_deploy.ovirt.api.fqdn }}"
        ca_file:  "{{ xtoph_deploy.ovirt.engine_cafile | default(omit) }}"
        insecure: "{{ xtoph_deploy.ovirt.insecure |  default(true) }}"
        username: "{{ ovirt_username }}"
        password: "{{ ovirt_password }}"
        state:    present
   
 

    ##
    ##    This block groups tasks related
    ##    to finishing a kickstart (ISO) deployment
    ##

    ##
    ##    NOTE: All kickstarts are assumed to shutdown
    ##          at completion.  That's how we now it
    ##          finished.
    ##



    - block:
    
          - name: "ovirt-deploy-monitor : wait for vm shutdown"
            ovirt_vm_info:
              pattern: name="{{ xtoph_deploy.ovirt.vm.name }}" cluster="{{ xtoph_deploy.ovirt.cluster_name }}"
              auth: "{{ ovirt_auth }}"
            register: vminfo_result
            until: vminfo_result.ovirt_vms[0].status == "down"
            retries: 600
            delay: 5
            when: deploy_node == true
      
          - name: "ovirt-deploy-monitor : eject iso"
            ovirt_vm:
              auth: "{{ ovirt_auth }}"
              name: "{{ xtoph_deploy.ovirt.vm.name }}"
              cluster: "{{ xtoph_deploy.ovirt.cluster_name }}"
              cd_iso: ""
      
          - name: "ovirt-deploy-monitor : vm change boot device to hd"
            ovirt_vm:
              auth: "{{ ovirt_auth }}"
              name: "{{ xtoph_deploy.ovirt.vm.name }}"
              cluster: "{{ xtoph_deploy.ovirt.cluster_name }}"
              boot_menu: "no"
              boot_devices:
                - hd
      
          - name: "ovirt-deploy-monitor : vm change state to RUNNING (BOOT)"
            ovirt_vm:
              auth: "{{ ovirt_auth }}"
              name: "{{ xtoph_deploy.ovirt.vm.name }}"
              cluster: "{{ xtoph_deploy.ovirt.cluster_name }}"
              state: "running"
              wait: yes
            retries: 3
      
          - name: "ovirt-deploy-monitor : undeploy iso"
            ovirt_disk:
              auth: '{{ ovirt_auth }}'
              name: '{{ xtoph_deploy.ovirt.vm.name }}.iso'
              storage_domain: '{{ xtoph_deploy.ovirt.storage.domain }}'
              state: absent
              wait: yes

      when: 
        - xtoph_deploy.kickstart_profile is defined



    ##
    ##    Log out of the oVIRT API service
    ##



    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"




