## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##    These tasks configure the "deployhost" with oVirt support
##    and install software/services to support the deployments
##

##
##    Install the OVIRT SDK 
##



- name: "ovirt-setup : install oVirt supporting packages (sdk/api)"
  yum: name=python-ovirt-engine-sdk4 state=installed



