- name:    "xtoph-deploy (handler) : restart cockpit"
  listen:  "restart_cockpit"
  service: name="{{ item }}" state=restarted
  with_items:
    - "cockpit"
    - "cockpit.socket"



- name:    "xtoph_deploy (handler) : restart httpd"
  listen:  "restart_httpd"
  service: name="httpd" state=restarted



- name:    "xtoph_deploy (handler) : restart libvirtd"
  listen:  "restart_libvirtd"
  service: name="libvirtd" state=restarted



- name:    "xtoph_deploy (handler) : restart dnsmasq"
  listen:  "restart_dnsmasq"
  service: name="dnsmasq" state=restarted
  when: xtoph_deploy.deployhost.dnsmasq_enable == true
